### ISSUE TITLE
Error when trying to connect to RegulonDB

### ISSUE THREAD

**Issue by rioualen** [ComunidadBioInfo/regutools#33]
Hola!

I'm trying out Regutools for the first time and I stumbled upon an error when trying to connect to RegulonDB, using the code provided in the [Regutools main page](https://comunidadbioinfo.github.io/regutools/). I tried both the released version and the dev one. Here's what I get, any idea about what's going on?

```R
library('regutools')
## basic example code

## Connect to the RegulonDB database if necessary
if(!exists('regulondb_conn')) regulondb_conn <- connect_database()
```

```R
> library('regutools')
> ## Connect to the RegulonDB database if necessary
> if(!exists('regulondb_conn')) regulondb_conn <- connect_database()
snapshotDate(): 2020-10-27
adding rname 'https://www.dropbox.com/s/eod8vdq4fthvjcr/regulondb_v10.6.2_DM_sqlite3.db?dl=1'
Downloading: 530 B     
Error in BiocFileCache::bfcrpath(bfc, url) : 
  not all 'rnames' found or unique.
In addition: Warning messages:
1: In .local(conn, statement, ...) :
  partial argument match of 'param' to 'params'
2: In .local(conn, statement, ...) :
  partial argument match of 'param' to 'params'
3: download failed
  web resource path: 'https://www.dropbox.com/s/eod8vdq4fthvjcr/regulondb_v10.6.2_DM_sqlite3.db?dl=1'
  local file path: '/var/folders/k_/b9r_08sj4h7_js0y_l3hs9_80000gn/T//RtmpF1uAwO/BiocFileCache/b05c5ce46be8_regulondb_v10.6.2_DM_sqlite3.db%3Fdl%3D1'
  reason: Not Found (HTTP 404). 
4: In .local(conn, statement, ...) :
  partial argument match of 'param' to 'params'
5: bfcadd() failed; resource removed
  rid: BFC2
  fpath: 'https://www.dropbox.com/s/eod8vdq4fthvjcr/regulondb_v10.6.2_DM_sqlite3.db?dl=1'
  reason: download failed 
6: In value[[3L]](cond) : 
trying to add rname 'https://www.dropbox.com/s/eod8vdq4fthvjcr/regulondb_v10.6.2_DM_sqlite3.db?dl=1' produced error:
  bfcadd() failed; see warnings()
> traceback()
4: stop("not all 'rnames' found or unique.")
3: BiocFileCache::bfcrpath(bfc, url)
2: BiocFileCache::bfcrpath(bfc, url)
1: connect_database()
```

```R
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] regutools_1.2.0

loaded via a namespace (and not attached):
  [1] colorspace_2.0-0              ellipsis_0.3.1                rprojroot_2.0.2               biovizBase_1.38.0            
  [5] htmlTable_2.1.0               XVector_0.30.0                GenomicRanges_1.42.0          base64enc_0.1-3              
  [9] dichromat_2.0-0               rstudioapi_0.13               remotes_2.2.0                 bit64_4.0.5                  
 [13] fansi_0.4.1                   interactiveDisplayBase_1.28.0 AnnotationDbi_1.52.0          xml2_1.3.2                   
 [17] splines_4.0.3                 R.methodsS3_1.8.1             knitr_1.30                    Formula_1.2-4                
 [21] Rsamtools_2.6.0               cluster_2.1.0                 dbplyr_2.0.0                  R.oo_1.24.0                  
 [25] png_0.1-7                     graph_1.68.0                  shiny_1.5.0                   BiocManager_1.30.10          
 [29] compiler_4.0.3                httr_1.4.2                    backports_1.2.0               assertthat_0.2.1             
 [33] Matrix_1.2-18                 fastmap_1.0.1                 lazyeval_0.2.2                cli_2.2.0                    
 [37] later_1.1.0.1                 htmltools_0.5.0               prettyunits_1.1.1             tools_4.0.3                  
 [41] igraph_1.2.6                  gtable_0.3.0                  glue_1.4.2                    GenomeInfoDbData_1.2.4       
 [45] dplyr_1.0.2                   rappdirs_0.3.1                Rcpp_1.0.5                    Biobase_2.50.0               
 [49] RJSONIO_1.3-1.4               vctrs_0.3.5                   Biostrings_2.58.0             rtracklayer_1.50.0           
 [53] xfun_0.19                     stringr_1.4.0                 ps_1.4.0                      RCy3_2.10.2                  
 [57] mime_0.9                      lifecycle_0.2.0               ensembldb_2.14.0              XML_3.99-0.5                 
 [61] AnnotationHub_2.22.0          zlibbioc_1.36.0               scales_1.1.1                  BSgenome_1.58.0              
 [65] VariantAnnotation_1.36.0      hms_0.5.3                     promises_1.1.1                MatrixGenerics_1.2.0         
 [69] ProtGenerics_1.22.0           parallel_4.0.3                SummarizedExperiment_1.20.0   AnnotationFilter_1.14.0      
 [73] RColorBrewer_1.1-2            yaml_2.2.1                    curl_4.3                      memoise_1.1.0                
 [77] gridExtra_2.3                 ggplot2_3.3.2                 biomaRt_2.46.0                rpart_4.1-15                 
 [81] latticeExtra_0.6-29           stringi_1.5.3                 RSQLite_2.2.1                 BiocVersion_3.12.0           
 [85] S4Vectors_0.28.0              checkmate_2.0.0               GenomicFeatures_1.42.1        BiocGenerics_0.36.0          
 [89] pkgbuild_1.1.0                BiocParallel_1.24.1           GenomeInfoDb_1.26.1           rlang_0.4.8                  
 [93] pkgconfig_2.0.3               matrixStats_0.57.0            bitops_1.0-6                  lattice_0.20-41              
 [97] purrr_0.3.4                   GenomicAlignments_1.26.0      htmlwidgets_1.5.2             processx_3.4.4               
[101] bit_4.0.4                     tidyselect_1.1.0              magrittr_2.0.1                R6_2.5.0                     
[105] IRanges_2.24.0                generics_0.1.0                Hmisc_4.4-1                   DelayedArray_0.16.0          
[109] DBI_1.1.0                     withr_2.3.0                   pillar_1.4.7                  foreign_0.8-80               
[113] survival_3.2-7                RCurl_1.98-1.2                nnet_7.3-14                   tibble_3.0.4                 
[117] crayon_1.3.4                  BiocFileCache_1.14.0          jpeg_0.1-8.1                  progress_1.2.2               
[121] grid_4.0.3                    data.table_1.13.2             callr_3.5.1                   blob_1.2.1                   
[125] digest_0.6.27                 xtable_1.8-4                  httpuv_1.5.4                  R.utils_2.10.1               
[129] openssl_1.4.3                 stats4_4.0.3                  munsell_0.5.0                 Gviz_1.34.0                  
[133] askpass_1.1
```

**Comment by lcolladotor** [comment]
Hi @rioualen,

Thanks for the report! I see that the Dropbox link to the data had changed. This is now fixed on version 1.2.1 and 1.3.1 which correspond to Bioconductor 3.12 (release) and 3.13 (devel). It'll take about 2 days for the updated `regutools` versions to be available through Bioc. If you want, you could also install version 1.3.1 using `BiocManager::install("ComunidadBioinfo/regutools")` (v1.2.1 is available from the `RELEASE_3_12` branch).

@jemilianosf @CarBarJon @josschavezf we should also finalize the data submission to `AnnotationHub` to avoid having to rely on our Dropbox backup.

Best,
Leo

**Comment by rioualen** [comment]
Thanks @lcolladotor!

I've reinstalled regutools but I'm still having an issue, is there something more I need to do? I'm running on Bioconductor 3.12, should I switch to 3.13?

```
> remove.packages("regutools")
Removing package from '/Library/Frameworks/R.framework/Versions/4.0/Resources/library'
(as 'lib' is unspecified)
> BiocManager::install("ComunidadBioinfo/regutools")
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)
Installing github package(s) 'ComunidadBioinfo/regutools'
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo ComunidadBioinfo/regutools@HEAD
✓  checking for file ‘/private/var/folders/k_/b9r_08sj4h7_js0y_l3hs9_80000gn/T/RtmpF1uAwO/remotesb05c443ecf1a/ComunidadBioInfo-regutools-5330c34/DESCRIPTION’ ...
─  preparing ‘regutools’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘regutools_1.3.1.tar.gz’
   
* installing *source* package ‘regutools’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (regutools)
> library('regutools')
> ## Connect to the RegulonDB database if necessary
> if(!exists('regulondb_conn')) regulondb_conn <- connect_database()
snapshotDate(): 2020-10-27
adding rname 'https://www.dropbox.com/s/eod8vdq4fthvjcr/regulondb_v10.6.2_DM_sqlite3.db?dl=1'
Downloading: 530 B     
Error in BiocFileCache::bfcrpath(bfc, url) : 
  not all 'rnames' found or unique.
In addition: Warning messages:
1: In .local(conn, statement, ...) :
  partial argument match of 'param' to 'params'
2: In .local(conn, statement, ...) :
  partial argument match of 'param' to 'params'
3: download failed
  web resource path: 'https://www.dropbox.com/s/eod8vdq4fthvjcr/regulondb_v10.6.2_DM_sqlite3.db?dl=1'
  local file path: '/var/folders/k_/b9r_08sj4h7_js0y_l3hs9_80000gn/T//RtmpF1uAwO/BiocFileCache/b05c647fd563_regulondb_v10.6.2_DM_sqlite3.db%3Fdl%3D1'
  reason: Not Found (HTTP 404). 
4: In .local(conn, statement, ...) :
  partial argument match of 'param' to 'params'
5: bfcadd() failed; resource removed
  rid: BFC4
  fpath: 'https://www.dropbox.com/s/eod8vdq4fthvjcr/regulondb_v10.6.2_DM_sqlite3.db?dl=1'
  reason: download failed 
6: In value[[3L]](cond) : 
trying to add rname 'https://www.dropbox.com/s/eod8vdq4fthvjcr/regulondb_v10.6.2_DM_sqlite3.db?dl=1' produced error:
  bfcadd() failed; see warnings()
```

**Comment by lcolladotor** [comment]
Hi Claire,

I think that you need to use a fresh R session. Maybe you had already loaded `regutools` in the R session where you updated it to version 1.3.1 which makes it hard to detect the changes. I think that's the solution because in your error report (`traceback()`) I see the old URL still.

Best,
Leo


```R
> library("regutools")
> library("sessioninfo")
> if (!exists("regulondb_conn")) regulondb_conn <- connect_database()
snapshotDate(): 2020-10-27
> options(width = 120)
> session_info()
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       macOS Catalina 10.15.7      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2020-11-25                  

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────
 package                * version  date       lib source                                     
 AnnotationDbi            1.52.0   2020-10-27 [1] Bioconductor                               
 AnnotationFilter         1.14.0   2020-10-27 [1] Bioconductor                               
 AnnotationHub            2.22.0   2020-10-27 [1] Bioconductor                               
 askpass                  1.1      2019-01-13 [1] CRAN (R 4.0.2)                             
 assertthat               0.2.1    2019-03-21 [1] CRAN (R 4.0.2)                             
 backports                1.2.0    2020-11-02 [1] CRAN (R 4.0.3)                             
 base64enc                0.1-3    2015-07-28 [1] CRAN (R 4.0.2)                             
 Biobase                  2.50.0   2020-10-27 [1] Bioconductor                               
 BiocFileCache            1.14.0   2020-10-27 [1] Bioconductor                               
 BiocGenerics             0.36.0   2020-10-27 [1] Bioconductor                               
 BiocManager              1.30.10  2019-11-16 [1] CRAN (R 4.0.2)                             
 BiocParallel             1.24.1   2020-11-06 [1] Bioconductor                               
 BiocVersion              3.12.0   2020-05-14 [1] Bioconductor                               
 biomaRt                  2.46.0   2020-10-27 [1] Bioconductor                               
 Biostrings               2.58.0   2020-10-27 [1] Bioconductor                               
 biovizBase               1.38.0   2020-10-27 [1] Bioconductor                               
 bit                      4.0.4    2020-08-04 [1] CRAN (R 4.0.2)                             
 bit64                    4.0.5    2020-08-30 [1] CRAN (R 4.0.2)                             
 bitops                   1.0-6    2013-08-17 [1] CRAN (R 4.0.2)                             
 blob                     1.2.1    2020-01-20 [1] CRAN (R 4.0.2)                             
 BSgenome                 1.58.0   2020-10-27 [1] Bioconductor                               
 callr                    3.5.1    2020-10-13 [1] CRAN (R 4.0.2)                             
 checkmate                2.0.0    2020-02-06 [1] CRAN (R 4.0.2)                             
 cli                      2.2.0    2020-11-20 [1] CRAN (R 4.0.2)                             
 cluster                  2.1.0    2019-06-19 [1] CRAN (R 4.0.3)                             
 colorout                 1.2-2    2020-11-03 [1] Github (jalvesaq/colorout@726d681)         
 colorspace               2.0-0    2020-11-11 [1] CRAN (R 4.0.2)                             
 crayon                   1.3.4    2017-09-16 [1] CRAN (R 4.0.2)                             
 curl                     4.3      2019-12-02 [1] CRAN (R 4.0.1)                             
 data.table               1.13.2   2020-10-19 [1] CRAN (R 4.0.2)                             
 DBI                      1.1.0    2019-12-15 [1] CRAN (R 4.0.2)                             
 dbplyr                   2.0.0    2020-11-03 [1] CRAN (R 4.0.3)                             
 DelayedArray             0.16.0   2020-10-27 [1] Bioconductor                               
 desc                     1.2.0    2018-05-01 [1] CRAN (R 4.0.2)                             
 devtools               * 2.3.2    2020-09-18 [1] CRAN (R 4.0.2)                             
 dichromat                2.0-0    2013-01-24 [1] CRAN (R 4.0.2)                             
 digest                   0.6.27   2020-10-24 [1] CRAN (R 4.0.2)                             
 dplyr                    1.0.2    2020-08-18 [1] CRAN (R 4.0.2)                             
 ellipsis                 0.3.1    2020-05-15 [1] CRAN (R 4.0.2)                             
 ensembldb                2.14.0   2020-10-27 [1] Bioconductor                               
 fansi                    0.4.1    2020-01-08 [1] CRAN (R 4.0.2)                             
 fastmap                  1.0.1    2019-10-08 [1] CRAN (R 4.0.2)                             
 foreign                  0.8-80   2020-05-24 [1] CRAN (R 4.0.3)                             
 Formula                  1.2-4    2020-10-16 [1] CRAN (R 4.0.2)                             
 fs                       1.5.0    2020-07-31 [1] CRAN (R 4.0.2)                             
 generics                 0.1.0    2020-10-31 [1] CRAN (R 4.0.2)                             
 GenomeInfoDb             1.26.1   2020-11-18 [1] Bioconductor                               
 GenomeInfoDbData         1.2.4    2020-11-03 [1] Bioconductor                               
 GenomicAlignments        1.26.0   2020-10-27 [1] Bioconductor                               
 GenomicFeatures          1.42.1   2020-11-11 [1] Bioconductor                               
 GenomicRanges            1.42.0   2020-10-27 [1] Bioconductor                               
 ggplot2                  3.3.2    2020-06-19 [1] CRAN (R 4.0.2)                             
 glue                     1.4.2    2020-08-27 [1] CRAN (R 4.0.2)                             
 graph                    1.68.0   2020-10-27 [1] Bioconductor                               
 gridExtra                2.3      2017-09-09 [1] CRAN (R 4.0.2)                             
 gtable                   0.3.0    2019-03-25 [1] CRAN (R 4.0.2)                             
 Gviz                     1.34.0   2020-10-27 [1] Bioconductor                               
 Hmisc                    4.4-1    2020-08-10 [1] CRAN (R 4.0.2)                             
 hms                      0.5.3    2020-01-08 [1] CRAN (R 4.0.2)                             
 htmlTable                2.1.0    2020-09-16 [1] CRAN (R 4.0.2)                             
 htmltools                0.5.0    2020-06-16 [1] CRAN (R 4.0.2)                             
 htmlwidgets              1.5.2    2020-10-03 [1] CRAN (R 4.0.2)                             
 httpuv                   1.5.4    2020-06-06 [1] CRAN (R 4.0.2)                             
 httr                     1.4.2    2020-07-20 [1] CRAN (R 4.0.2)                             
 igraph                   1.2.6    2020-10-06 [1] CRAN (R 4.0.2)                             
 interactiveDisplayBase   1.28.0   2020-10-27 [1] Bioconductor                               
 IRanges                  2.24.0   2020-10-27 [1] Bioconductor                               
 jpeg                     0.1-8.1  2019-10-24 [1] CRAN (R 4.0.2)                             
 knitr                    1.30     2020-09-22 [1] CRAN (R 4.0.2)                             
 later                    1.1.0.1  2020-06-05 [1] CRAN (R 4.0.2)                             
 lattice                  0.20-41  2020-04-02 [1] CRAN (R 4.0.3)                             
 latticeExtra             0.6-29   2019-12-19 [1] CRAN (R 4.0.2)                             
 lazyeval                 0.2.2    2019-03-15 [1] CRAN (R 4.0.2)                             
 lifecycle                0.2.0    2020-03-06 [1] CRAN (R 4.0.2)                             
 lubridate                1.7.9.2  2020-11-13 [1] CRAN (R 4.0.2)                             
 magrittr                 2.0.1    2020-11-17 [1] CRAN (R 4.0.2)                             
 Matrix                   1.2-18   2019-11-27 [1] CRAN (R 4.0.3)                             
 MatrixGenerics           1.2.0    2020-10-27 [1] Bioconductor                               
 matrixStats              0.57.0   2020-09-25 [1] CRAN (R 4.0.2)                             
 memoise                  1.1.0    2017-04-21 [1] CRAN (R 4.0.2)                             
 mime                     0.9      2020-02-04 [1] CRAN (R 4.0.2)                             
 munsell                  0.5.0    2018-06-12 [1] CRAN (R 4.0.2)                             
 nnet                     7.3-14   2020-04-26 [1] CRAN (R 4.0.3)                             
 openssl                  1.4.3    2020-09-18 [1] CRAN (R 4.0.2)                             
 pillar                   1.4.7    2020-11-20 [1] CRAN (R 4.0.2)                             
 pkgbuild                 1.1.0    2020-07-13 [1] CRAN (R 4.0.2)                             
 pkgconfig                2.0.3    2019-09-22 [1] CRAN (R 4.0.2)                             
 pkgload                  1.1.0    2020-05-29 [1] CRAN (R 4.0.2)                             
 png                      0.1-7    2013-12-03 [1] CRAN (R 4.0.2)                             
 prettyunits              1.1.1    2020-01-24 [1] CRAN (R 4.0.2)                             
 processx                 3.4.4    2020-09-03 [1] CRAN (R 4.0.2)                             
 progress                 1.2.2    2019-05-16 [1] CRAN (R 4.0.2)                             
 promises                 1.1.1    2020-06-09 [1] CRAN (R 4.0.2)                             
 ProtGenerics             1.22.0   2020-10-27 [1] Bioconductor                               
 ps                       1.4.0    2020-10-07 [1] CRAN (R 4.0.2)                             
 purrr                    0.3.4    2020-04-17 [1] CRAN (R 4.0.2)                             
 R.methodsS3              1.8.1    2020-08-26 [1] CRAN (R 4.0.2)                             
 R.oo                     1.24.0   2020-08-26 [1] CRAN (R 4.0.2)                             
 R.utils                  2.10.1   2020-08-26 [1] CRAN (R 4.0.2)                             
 R6                       2.5.0    2020-10-28 [1] CRAN (R 4.0.2)                             
 rappdirs                 0.3.1    2016-03-28 [1] CRAN (R 4.0.2)                             
 RColorBrewer             1.1-2    2014-12-07 [1] CRAN (R 4.0.2)                             
 Rcpp                     1.0.5    2020-07-06 [1] CRAN (R 4.0.2)                             
 RCurl                    1.98-1.2 2020-04-18 [1] CRAN (R 4.0.2)                             
 RCy3                     2.10.2   2020-11-19 [1] Bioconductor                               
 regutools              * 1.3.1    2020-11-25 [1] Github (ComunidadBioinfo/regutools@5330c34)
 remotes                  2.2.0    2020-07-21 [1] CRAN (R 4.0.2)                             
 RJSONIO                  1.3-1.4  2020-01-15 [1] CRAN (R 4.0.2)                             
 rlang                    0.4.8    2020-10-08 [1] CRAN (R 4.0.2)                             
 rpart                    4.1-15   2019-04-12 [1] CRAN (R 4.0.3)                             
 rprojroot                2.0.2    2020-11-15 [1] CRAN (R 4.0.2)                             
 Rsamtools                2.6.0    2020-10-27 [1] Bioconductor                               
 RSQLite                  2.2.1    2020-09-30 [1] CRAN (R 4.0.2)                             
 rsthemes                 0.1.0    2020-11-03 [1] Github (gadenbuie/rsthemes@6391fe5)        
 rstudioapi               0.13     2020-11-12 [1] CRAN (R 4.0.2)                             
 rtracklayer              1.50.0   2020-10-27 [1] Bioconductor                               
 S4Vectors                0.28.0   2020-10-27 [1] Bioconductor                               
 scales                   1.1.1    2020-05-11 [1] CRAN (R 4.0.2)                             
 sessioninfo            * 1.1.1    2018-11-05 [1] CRAN (R 4.0.2)                             
 shiny                    1.5.0    2020-06-23 [1] CRAN (R 4.0.2)                             
 stringi                  1.5.3    2020-09-09 [1] CRAN (R 4.0.2)                             
 stringr                  1.4.0    2019-02-10 [1] CRAN (R 4.0.2)                             
 SummarizedExperiment     1.20.0   2020-10-27 [1] Bioconductor                               
 suncalc                  0.5.0    2019-04-03 [1] CRAN (R 4.0.2)                             
 survival                 3.2-7    2020-09-28 [1] CRAN (R 4.0.3)                             
 testthat               * 3.0.0    2020-10-31 [1] CRAN (R 4.0.2)                             
 tibble                   3.0.4    2020-10-12 [1] CRAN (R 4.0.2)                             
 tidyselect               1.1.0    2020-05-11 [1] CRAN (R 4.0.2)                             
 usethis                * 1.6.3    2020-09-17 [1] CRAN (R 4.0.2)                             
 VariantAnnotation        1.36.0   2020-10-28 [1] Bioconductor                               
 vctrs                    0.3.5    2020-11-17 [1] CRAN (R 4.0.2)                             
 withr                    2.3.0    2020-09-22 [1] CRAN (R 4.0.2)                             
 xfun                     0.19     2020-10-30 [1] CRAN (R 4.0.2)                             
 XML                      3.99-0.5 2020-07-23 [1] CRAN (R 4.0.2)                             
 xml2                     1.3.2    2020-04-23 [1] CRAN (R 4.0.2)                             
 xtable                   1.8-4    2019-04-21 [1] CRAN (R 4.0.2)                             
 XVector                  0.30.0   2020-10-28 [1] Bioconductor                               
 yaml                     2.2.1    2020-02-01 [1] CRAN (R 4.0.2)                             
 zlibbioc                 1.36.0   2020-10-28 [1] Bioconductor                               

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

**Comment by josschavezf** [comment]
Hi @rioualen ,  I think was my fault, sorry. I have been re-organizing my Dropbox and accidentally moved the file to a new location, but is back to its place. I think it should work now. Please let me know if it's working.

**Comment by rioualen** [comment]
It's working just fine now, thank you guys for answering so fast!
